const input_data_yahoo_jp = [

    {
        "ip": "193.73.125.35",
        "city": "Windisch",
        "region": "Aargau",
        "region_code": "AG",
        "country": "CH",
        "country_name": "Switzerland",
        "continent_code": "EU",
        "in_eu": false,
        "postal": "5210",
        "latitude": 47.479,
        "longitude": 8.2184,
        "timezone": "Europe/Zurich",
        "utc_offset": "+0200",
        "country_calling_code": "+41",
        "currency": "CHF",
        "languages": "de-CH,fr-CH,it-CH,rm",
        "asn": "AS559",
        "org": "SWITCH"
    },
    {
        "ip": "192.43.192.196",
        "city": "Basel",
        "region": "Basel-City",
        "region_code": "BS",
        "country": "CH",
        "country_name": "Switzerland",
        "continent_code": "EU",
        "in_eu": false,
        "postal": "4001",
        "latitude": 47.5584,
        "longitude": 7.5733,
        "timezone": "Europe/Zurich",
        "utc_offset": "+0200",
        "country_calling_code": "+41",
        "currency": "CHF",
        "languages": "de-CH,fr-CH,it-CH,rm",
        "asn": "AS559",
        "org": "SWITCH"
    },
    {
        "ip": "130.59.37.34",
        "city": "Zurich",
        "region": "Zurich",
        "region_code": "ZH",
        "country": "CH",
        "country_name": "Switzerland",
        "continent_code": "EU",
        "in_eu": false,
        "postal": "8002",
        "latitude": 47.3664,
        "longitude": 8.5546,
        "timezone": "Europe/Zurich",
        "utc_offset": "+0200",
        "country_calling_code": "+41",
        "currency": "CHF",
        "languages": "de-CH,fr-CH,it-CH,rm",
        "asn": "AS559",
        "org": "SWITCH"
    },
    {
        "ip": "130.59.36.170",
        "city": "Zurich",
        "region": "Zurich",
        "region_code": "ZH",
        "country": "CH",
        "country_name": "Switzerland",
        "continent_code": "EU",
        "in_eu": false,
        "postal": "8002",
        "latitude": 47.3664,
        "longitude": 8.5546,
        "timezone": "Europe/Zurich",
        "utc_offset": "+0200",
        "country_calling_code": "+41",
        "currency": "CHF",
        "languages": "de-CH,fr-CH,it-CH,rm",
        "asn": "AS559",
        "org": "SWITCH"
    },
    {
        "ip": "130.59.38.109",
        "city": "Zurich",
        "region": "Zurich",
        "region_code": "ZH",
        "country": "CH",
        "country_name": "Switzerland",
        "continent_code": "EU",
        "in_eu": false,
        "postal": "8002",
        "latitude": 47.3664,
        "longitude": 8.5546,
        "timezone": "Europe/Zurich",
        "utc_offset": "+0200",
        "country_calling_code": "+41",
        "currency": "CHF",
        "languages": "de-CH,fr-CH,it-CH,rm",
        "asn": "AS559",
        "org": "SWITCH"
    },
    {
        "ip": "213.248.79.189",
        "city": "New York",
        "region": "New York",
        "region_code": "NY",
        "country": "US",
        "country_name": "United States",
        "continent_code": "NA",
        "in_eu": false,
        "postal": "10023",
        "latitude": 40.782,
        "longitude": -73.9953,
        "timezone": "America/New_York",
        "utc_offset": "-0400",
        "country_calling_code": "+1",
        "currency": "USD",
        "languages": "en-US,es-US,haw,fr",
        "asn": "AS1299",
        "org": "Telia Company AB"
    },
    {
        "ip": "62.115.142.104",
        "city": "London",
        "region": "England",
        "region_code": "ENG",
        "country": "GB",
        "country_name": "United Kingdom",
        "continent_code": "EU",
        "in_eu": true,
        "postal": "SE15",
        "latitude": 51.4663,
        "longitude": -0.051,
        "timezone": "Europe/London",
        "utc_offset": "+0100",
        "country_calling_code": "+44",
        "currency": "GBP",
        "languages": "en-GB,cy-GB,gd",
        "asn": "AS1299",
        "org": "Telia Company AB"
    },
    {
        "ip": "62.115.112.239",
        "city": "London",
        "region": "England",
        "region_code": "ENG",
        "country": "GB",
        "country_name": "United Kingdom",
        "continent_code": "EU",
        "in_eu": true,
        "postal": "SE15",
        "latitude": 51.4663,
        "longitude": -0.051,
        "timezone": "Europe/London",
        "utc_offset": "+0100",
        "country_calling_code": "+44",
        "currency": "GBP",
        "languages": "en-GB,cy-GB,gd",
        "asn": "AS1299",
        "org": "Telia Company AB"
    },
    {
        "ip": "62.115.112.231",
        "city": "London",
        "region": "England",
        "region_code": "ENG",
        "country": "GB",
        "country_name": "United Kingdom",
        "continent_code": "EU",
        "in_eu": true,
        "postal": "SE15",
        "latitude": 51.4663,
        "longitude": -0.051,
        "timezone": "Europe/London",
        "utc_offset": "+0100",
        "country_calling_code": "+44",
        "currency": "GBP",
        "languages": "en-GB,cy-GB,gd",
        "asn": "AS1299",
        "org": "Telia Company AB"
    },
    {
        "ip": "62.115.122.245",
        "city": "London",
        "region": "England",
        "region_code": "ENG",
        "country": "GB",
        "country_name": "United Kingdom",
        "continent_code": "EU",
        "in_eu": true,
        "postal": "SE15",
        "latitude": 51.4663,
        "longitude": -0.051,
        "timezone": "Europe/London",
        "utc_offset": "+0100",
        "country_calling_code": "+44",
        "currency": "GBP",
        "languages": "en-GB,cy-GB,gd",
        "asn": "AS1299",
        "org": "Telia Company AB"
    },
    {
        "ip": "62.115.141.147",
        "city": "London",
        "region": "England",
        "region_code": "ENG",
        "country": "GB",
        "country_name": "United Kingdom",
        "continent_code": "EU",
        "in_eu": true,
        "postal": "SE15",
        "latitude": 51.4663,
        "longitude": -0.051,
        "timezone": "Europe/London",
        "utc_offset": "+0100",
        "country_calling_code": "+44",
        "currency": "GBP",
        "languages": "en-GB,cy-GB,gd",
        "asn": "AS1299",
        "org": "Telia Company AB"
    },
    {
        "ip": "202.232.1.69",
        "city": "Osaka",
        "region": "Ōsaka",
        "region_code": "27",
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": "543-0062",
        "latitude": 34.6869,
        "longitude": 135.5211,
        "timezone": "Asia/Tokyo",
        "utc_offset": "+0900",
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS2497",
        "org": "Internet Initiative Japan Inc."
    },
    {
        "ip": "58.138.98.29",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS2497",
        "org": "Internet Initiative Japan Inc."
    },
    {
        "ip": "62.115.141.147",
        "city": "London",
        "region": "England",
        "region_code": "ENG",
        "country": "GB",
        "country_name": "United Kingdom",
        "continent_code": "EU",
        "in_eu": true,
        "postal": "SE15",
        "latitude": 51.4663,
        "longitude": -0.051,
        "timezone": "Europe/London",
        "utc_offset": "+0100",
        "country_calling_code": "+44",
        "currency": "GBP",
        "languages": "en-GB,cy-GB,gd",
        "asn": "AS1299",
        "org": "Telia Company AB"
    },
    {
        "ip": "58.138.98.29",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS2497",
        "org": "Internet Initiative Japan Inc."
    },
    {
        "ip": "58.138.106.122",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS2497",
        "org": "Internet Initiative Japan Inc."
    },
    {
        "ip": "58.138.98.29",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS2497",
        "org": "Internet Initiative Japan Inc."
    },
    {
        "ip": "210.138.106.238",
        "city": "Osaka",
        "region": "Ōsaka",
        "region_code": "27",
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": "543-0062",
        "latitude": 34.6869,
        "longitude": 135.5211,
        "timezone": "Asia/Tokyo",
        "utc_offset": "+0900",
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS2497",
        "org": "Internet Initiative Japan Inc."
    },
    {
        "ip": "210.138.106.238",
        "city": "Osaka",
        "region": "Ōsaka",
        "region_code": "27",
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": "543-0062",
        "latitude": 34.6869,
        "longitude": 135.5211,
        "timezone": "Asia/Tokyo",
        "utc_offset": "+0900",
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS2497",
        "org": "Internet Initiative Japan Inc."
    },
    {
        "ip": "124.83.228.54",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS24572",
        "org": "Yahoo Japan"
    },
    {
        "ip": "124.83.252.170",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS24572",
        "org": "Yahoo Japan"
    },
    {
        "ip": "58.138.106.122",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS2497",
        "org": "Internet Initiative Japan Inc."
    },
    {
        "ip": "124.83.252.170",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS24572",
        "org": "Yahoo Japan"
    },
    {
        "ip": "114.111.64.202",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS24572",
        "org": "Yahoo Japan"
    },
    {
        "ip": "124.83.252.170",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS24572",
        "org": "Yahoo Japan"
    },
    {
        "ip": "114.111.64.202",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS24572",
        "org": "Yahoo Japan"
    },
    {
        "ip": "183.79.135.206",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS24572",
        "org": "Yahoo Japan"
    }

]

