const input_data_yahoo_jp = [

    {
        "ip": "193.73.125.35",
        "city": "Windisch",
        "region": "Aargau",
        "region_code": "AG",
        "country": "CH",
        "country_name": "Switzerland",
        "continent_code": "EU",
        "in_eu": false,
        "postal": "5210",
        "latitude": 47.479,
        "longitude": 8.2184,
        "timezone": "Europe/Zurich",
        "utc_offset": "+0200",
        "country_calling_code": "+41",
        "currency": "CHF",
        "languages": "de-CH,fr-CH,it-CH,rm",
        "asn": "AS559",
        "org": "SWITCH"
    },
    {
        "ip": "192.43.192.196",
        "city": "Basel",
        "region": "Basel-City",
        "region_code": "BS",
        "country": "CH",
        "country_name": "Switzerland",
        "continent_code": "EU",
        "in_eu": false,
        "postal": "4001",
        "latitude": 47.5584,
        "longitude": 7.5733,
        "timezone": "Europe/Zurich",
        "utc_offset": "+0200",
        "country_calling_code": "+41",
        "currency": "CHF",
        "languages": "de-CH,fr-CH,it-CH,rm",
        "asn": "AS559",
        "org": "SWITCH"
    },
    {
        "ip": "130.59.37.34",
        "city": "Zurich",
        "region": "Zurich",
        "region_code": "ZH",
        "country": "CH",
        "country_name": "Switzerland",
        "continent_code": "EU",
        "in_eu": false,
        "postal": "8002",
        "latitude": 47.3664,
        "longitude": 8.5546,
        "timezone": "Europe/Zurich",
        "utc_offset": "+0200",
        "country_calling_code": "+41",
        "currency": "CHF",
        "languages": "de-CH,fr-CH,it-CH,rm",
        "asn": "AS559",
        "org": "SWITCH"
    },
    {
        "ip": "130.59.36.170",
        "city": "Zurich",
        "region": "Zurich",
        "region_code": "ZH",
        "country": "CH",
        "country_name": "Switzerland",
        "continent_code": "EU",
        "in_eu": false,
        "postal": "8002",
        "latitude": 47.3664,
        "longitude": 8.5546,
        "timezone": "Europe/Zurich",
        "utc_offset": "+0200",
        "country_calling_code": "+41",
        "currency": "CHF",
        "languages": "de-CH,fr-CH,it-CH,rm",
        "asn": "AS559",
        "org": "SWITCH"
    },
    {
        "ip": "130.59.38.109",
        "city": "Zurich",
        "region": "Zurich",
        "region_code": "ZH",
        "country": "CH",
        "country_name": "Switzerland",
        "continent_code": "EU",
        "in_eu": false,
        "postal": "8002",
        "latitude": 47.3664,
        "longitude": 8.5546,
        "timezone": "Europe/Zurich",
        "utc_offset": "+0200",
        "country_calling_code": "+41",
        "currency": "CHF",
        "languages": "de-CH,fr-CH,it-CH,rm",
        "asn": "AS559",
        "org": "SWITCH"
    },
    {
        "ip": "213.248.79.189",
        "city": "New York",
        "region": "New York",
        "region_code": "NY",
        "country": "US",
        "country_name": "United States",
        "continent_code": "NA",
        "in_eu": false,
        "postal": "10023",
        "latitude": 40.782,
        "longitude": -73.9953,
        "timezone": "America/New_York",
        "utc_offset": "-0400",
        "country_calling_code": "+1",
        "currency": "USD",
        "languages": "en-US,es-US,haw,fr",
        "asn": "AS1299",
        "org": "Telia Company AB"
    },
    {
        "ip": "62.115.142.104",
        "city": "London",
        "region": "England",
        "region_code": "ENG",
        "country": "GB",
        "country_name": "United Kingdom",
        "continent_code": "EU",
        "in_eu": true,
        "postal": "SE15",
        "latitude": 51.4663,
        "longitude": -0.051,
        "timezone": "Europe/London",
        "utc_offset": "+0100",
        "country_calling_code": "+44",
        "currency": "GBP",
        "languages": "en-GB,cy-GB,gd",
        "asn": "AS1299",
        "org": "Telia Company AB"
    },
    {
        "ip": "62.115.112.239",
        "city": "London",
        "region": "England",
        "region_code": "ENG",
        "country": "GB",
        "country_name": "United Kingdom",
        "continent_code": "EU",
        "in_eu": true,
        "postal": "SE15",
        "latitude": 51.4663,
        "longitude": -0.051,
        "timezone": "Europe/London",
        "utc_offset": "+0100",
        "country_calling_code": "+44",
        "currency": "GBP",
        "languages": "en-GB,cy-GB,gd",
        "asn": "AS1299",
        "org": "Telia Company AB"
    },
    {
        "ip": "62.115.112.231",
        "city": "London",
        "region": "England",
        "region_code": "ENG",
        "country": "GB",
        "country_name": "United Kingdom",
        "continent_code": "EU",
        "in_eu": true,
        "postal": "SE15",
        "latitude": 51.4663,
        "longitude": -0.051,
        "timezone": "Europe/London",
        "utc_offset": "+0100",
        "country_calling_code": "+44",
        "currency": "GBP",
        "languages": "en-GB,cy-GB,gd",
        "asn": "AS1299",
        "org": "Telia Company AB"
    },
    {
        "ip": "62.115.122.245",
        "city": "London",
        "region": "England",
        "region_code": "ENG",
        "country": "GB",
        "country_name": "United Kingdom",
        "continent_code": "EU",
        "in_eu": true,
        "postal": "SE15",
        "latitude": 51.4663,
        "longitude": -0.051,
        "timezone": "Europe/London",
        "utc_offset": "+0100",
        "country_calling_code": "+44",
        "currency": "GBP",
        "languages": "en-GB,cy-GB,gd",
        "asn": "AS1299",
        "org": "Telia Company AB"
    },
    {
        "ip": "62.115.141.147",
        "city": "London",
        "region": "England",
        "region_code": "ENG",
        "country": "GB",
        "country_name": "United Kingdom",
        "continent_code": "EU",
        "in_eu": true,
        "postal": "SE15",
        "latitude": 51.4663,
        "longitude": -0.051,
        "timezone": "Europe/London",
        "utc_offset": "+0100",
        "country_calling_code": "+44",
        "currency": "GBP",
        "languages": "en-GB,cy-GB,gd",
        "asn": "AS1299",
        "org": "Telia Company AB"
    },
    {
        "ip": "202.232.1.69",
        "city": "Osaka",
        "region": "Ōsaka",
        "region_code": "27",
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": "543-0062",
        "latitude": 34.6869,
        "longitude": 135.5211,
        "timezone": "Asia/Tokyo",
        "utc_offset": "+0900",
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS2497",
        "org": "Internet Initiative Japan Inc."
    },
    {
        "ip": "58.138.98.29",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS2497",
        "org": "Internet Initiative Japan Inc."
    },
    {
        "ip": "62.115.141.147",
        "city": "London",
        "region": "England",
        "region_code": "ENG",
        "country": "GB",
        "country_name": "United Kingdom",
        "continent_code": "EU",
        "in_eu": true,
        "postal": "SE15",
        "latitude": 51.4663,
        "longitude": -0.051,
        "timezone": "Europe/London",
        "utc_offset": "+0100",
        "country_calling_code": "+44",
        "currency": "GBP",
        "languages": "en-GB,cy-GB,gd",
        "asn": "AS1299",
        "org": "Telia Company AB"
    },
    {
        "ip": "58.138.98.29",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS2497",
        "org": "Internet Initiative Japan Inc."
    },
    {
        "ip": "58.138.106.122",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS2497",
        "org": "Internet Initiative Japan Inc."
    },
    {
        "ip": "58.138.98.29",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS2497",
        "org": "Internet Initiative Japan Inc."
    },
    {
        "ip": "210.138.106.238",
        "city": "Osaka",
        "region": "Ōsaka",
        "region_code": "27",
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": "543-0062",
        "latitude": 34.6869,
        "longitude": 135.5211,
        "timezone": "Asia/Tokyo",
        "utc_offset": "+0900",
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS2497",
        "org": "Internet Initiative Japan Inc."
    },
    {
        "ip": "210.138.106.238",
        "city": "Osaka",
        "region": "Ōsaka",
        "region_code": "27",
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": "543-0062",
        "latitude": 34.6869,
        "longitude": 135.5211,
        "timezone": "Asia/Tokyo",
        "utc_offset": "+0900",
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS2497",
        "org": "Internet Initiative Japan Inc."
    },
    {
        "ip": "124.83.228.54",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS24572",
        "org": "Yahoo Japan"
    },
    {
        "ip": "124.83.252.170",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS24572",
        "org": "Yahoo Japan"
    },
    {
        "ip": "58.138.106.122",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS2497",
        "org": "Internet Initiative Japan Inc."
    },
    {
        "ip": "124.83.252.170",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS24572",
        "org": "Yahoo Japan"
    },
    {
        "ip": "114.111.64.202",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS24572",
        "org": "Yahoo Japan"
    },
    {
        "ip": "124.83.252.170",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS24572",
        "org": "Yahoo Japan"
    },
    {
        "ip": "114.111.64.202",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS24572",
        "org": "Yahoo Japan"
    },
    {
        "ip": "183.79.135.206",
        "city": "Chiyoda",
        "region": "Tokyo",
        "region_code": null,
        "country": "JP",
        "country_name": "Japan",
        "continent_code": "AS",
        "in_eu": false,
        "postal": null,
        "latitude": 35.694003,
        "longitude": 139.753595,
        "timezone": null,
        "utc_offset": null,
        "country_calling_code": "+81",
        "currency": "JPY",
        "languages": "ja",
        "asn": "AS24572",
        "org": "Yahoo Japan"
    }

]

const input_data_soundcloud = [{ "ip": "193.73.125.34", "city": "Windisch", "region": "Aargau", "region_code": "AG", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "5210", "latitude": 47.479, "longitude": 8.2184, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "192.43.192.196", "city": "Basel", "region": "Basel-City", "region_code": "BS", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "4001", "latitude": 47.5584, "longitude": 7.5733, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.39.74", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.39.77", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.37.146", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.36.5", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "80.249.209.162", "city": "Amsterdam", "region": "North Holland", "region_code": "NH", "country": "NL", "country_name": "Netherlands", "continent_code": "EU", "in_eu": true, "postal": "1091", "latitude": 52.3534, "longitude": 4.9087, "timezone": "Europe/Amsterdam", "utc_offset": "+0200", "country_calling_code": "+31", "currency": "EUR", "languages": "nl-NL,fy-NL", "asn": "AS1200", "org": "Amsterdam Internet Exchange B.V." }, { "ip": "152.195.104.133", "city": "Amsterdam", "region": "North Holland", "region_code": "NH", "country": "NL", "country_name": "Netherlands", "continent_code": "EU", "in_eu": true, "postal": "1098", "latitude": 52.352, "longitude": 4.9392, "timezone": "Europe/Amsterdam", "utc_offset": "+0200", "country_calling_code": "+31", "currency": "EUR", "languages": "nl-NL,fy-NL", "asn": "AS15133", "org": "MCI Communications Services, Inc. d/b/a Verizon Business" }, { "ip": "93.184.220.127", "city": "London", "region": "England", "region_code": "ENG", "country": "GB", "country_name": "United Kingdom", "continent_code": "EU", "in_eu": true, "postal": "EC2V", "latitude": 51.5142, "longitude": -0.0931, "timezone": "Europe/London", "utc_offset": "+0100", "country_calling_code": "+44", "currency": "GBP", "languages": "en-GB,cy-GB,gd", "asn": "AS15133", "org": "MCI Communications Services, Inc. d/b/a Verizon Business" }, {
    "ip": "93.184.220.127", "city": "London", "region": "England", "region_code": "ENG", "country": "GB", "country_name": "United Kingdom", "continent_code": "EU", "in_eu": true, "postal": "EC2V", "latitude": 51.5142, "longitude": -0.0931, "timezone": "Europe/London", "utc_offset": "+0100", "country_calling_code": "+44", "currency": "GBP", "languages": "en-GB,cy-GB,gd", "asn": "AS15133",
    "org": "MCI Communications Services, Inc. d/b/a Verizon Business"
}]
const input_data_pornhub = [{ "ip": "193.73.125.35", "city": "Windisch", "region": "Aargau", "region_code": "AG", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "5210", "latitude": 47.479, "longitude": 8.2184, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "192.43.192.196", "city": "Basel", "region": "Basel-City", "region_code": "BS", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "4001", "latitude": 47.5584, "longitude": 7.5733, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.37.34", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.36.170", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.38.109", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "213.248.79.189", "city": "New York", "region": "New York", "region_code": "NY", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "10023", "latitude": 40.782, "longitude": -73.9953, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS1299", "org": "Telia Company AB" }, { "ip": "62.115.142.110", "city": "London", "region": "England", "region_code": "ENG", "country": "GB", "country_name": "United Kingdom", "continent_code": "EU", "in_eu": true, "postal": "SE15", "latitude": 51.4663, "longitude": -0.051, "timezone": "Europe/London", "utc_offset": "+0100", "country_calling_code": "+44", "currency": "GBP", "languages": "en-GB,cy-GB,gd", "asn": "AS1299", "org": "Telia Company AB" }, { "ip": "62.115.142.104", "city": "London", "region": "England", "region_code": "ENG", "country": "GB", "country_name": "United Kingdom", "continent_code": "EU", "in_eu": true, "postal": "SE15", "latitude": 51.4663, "longitude": -0.051, "timezone": "Europe/London", "utc_offset": "+0100", "country_calling_code": "+44", "currency": "GBP", "languages": "en-GB,cy-GB,gd", "asn": "AS1299", "org": "Telia Company AB" }, { "ip": "62.115.120.0", "city": "Frankfurt am Main", "region": "Hesse", "region_code": "HE", "country": "DE", "country_name": "Germany", "continent_code": "EU", "in_eu": true, "postal": "60313", "latitude": 50.1155, "longitude": 8.6842, "timezone": "Europe/Berlin", "utc_offset": "+0200", "country_calling_code": "+49", "currency": "EUR", "languages": "de", "asn": "AS1299", "org": "Telia Company AB" }, { "ip": "62.115.120.6", "city": "Frankfurt am Main", "region": "Hesse", "region_code": "HE", "country": "DE", "country_name": "Germany", "continent_code": "EU", "in_eu": true, "postal": "60313", "latitude": 50.1155, "longitude": 8.6842, "timezone": "Europe/Berlin", "utc_offset": "+0200", "country_calling_code": "+49", "currency": "EUR", "languages": "de", "asn": "AS1299", "org": "Telia Company AB" }]
const input_data_flightradar24 = [{ "ip": "193.73.125.35", "city": "Windisch", "region": "Aargau", "region_code": "AG", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "5210", "latitude": 47.479, "longitude": 8.2184, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "192.43.192.196", "city": "Basel", "region": "Basel-City", "region_code": "BS", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "4001", "latitude": 47.5584, "longitude": 7.5733, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.39.74", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.39.77", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.37.146", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.36.5", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "80.249.209.235", "city": "Amsterdam", "region": "North Holland", "region_code": "NH", "country": "NL", "country_name": "Netherlands", "continent_code": "EU", "in_eu": true, "postal": "1091", "latitude": 52.3534, "longitude": 4.9087, "timezone": "Europe/Amsterdam", "utc_offset": "+0200", "country_calling_code": "+31", "currency": "EUR", "languages": "nl-NL,fy-NL", "asn": "AS1200", "org": "Amsterdam Internet Exchange B.V." }, { "ip": "213.80.87.147", "city": "Uppsala", "region": "Uppsala", "region_code": "C", "country": "SE", "country_name": "Sweden", "continent_code": "EU", "in_eu": true, "postal": "753 81", "latitude": 59.8585, "longitude": 17.6454, "timezone": "Europe/Stockholm", "utc_offset": "+0200", "country_calling_code": "+46", "currency": "SEK", "languages": "sv-SE,se,sma,fi-SE", "asn": "AS12552", "org": "IP-Only Networks AB" }, { "ip": "185.218.24.12", "city": "Stockholm", "region": "Stockholm", "region_code": "AB", "country": "SE", "country_name": "Sweden", "continent_code": "EU", "in_eu": true, "postal": "173 11", "latitude": 59.3333, "longitude": 18.05, "timezone": "Europe/Stockholm", "utc_offset": "+0200", "country_calling_code": "+46", "currency": "SEK", "languages": "sv-SE,se,sma,fi-SE", "asn": "AS203092", "org": "Flightradar24 AB" }]
const input_data_baidu = [{ "ip": "193.73.125.35", "city": "Windisch", "region": "Aargau", "region_code": "AG", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "5210", "latitude": 47.479, "longitude": 8.2184, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "192.43.192.196", "city": "Basel", "region": "Basel-City", "region_code": "BS", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "4001", "latitude": 47.5584, "longitude": 7.5733, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.37.34", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.36.170", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.38.109", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "213.248.79.189", "city": "New York", "region": "New York", "region_code": "NY", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "10023", "latitude": 40.782, "longitude": -73.9953, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS1299", "org": "Telia Company AB" }, { "ip": "62.115.135.128", "city": "Stockholm", "region": "Stockholm", "region_code": "AB", "country": "SE", "country_name": "Sweden", "continent_code": "EU", "in_eu": true, "postal": "173 11", "latitude": 59.3333, "longitude": 18.05, "timezone": "Europe/Stockholm", "utc_offset": "+0200", "country_calling_code": "+46", "currency": "SEK", "languages": "sv-SE,se,sma,fi-SE", "asn": "AS1299", "org": "Telia Company AB" }, { "ip": "62.115.135.122", "city": "Stockholm", "region": "Stockholm", "region_code": "AB", "country": "SE", "country_name": "Sweden", "continent_code": "EU", "in_eu": true, "postal": "173 11", "latitude": 59.3333, "longitude": 18.05, "timezone": "Europe/Stockholm", "utc_offset": "+0200", "country_calling_code": "+46", "currency": "SEK", "languages": "sv-SE,se,sma,fi-SE", "asn": "AS1299", "org": "Telia Company AB" }, { "ip": "62.115.122.159", "city": "London", "region": "England", "region_code": "ENG", "country": "GB", "country_name": "United Kingdom", "continent_code": "EU", "in_eu": true, "postal": "SE15", "latitude": 51.4663, "longitude": -0.051, "timezone": "Europe/London", "utc_offset": "+0100", "country_calling_code": "+44", "currency": "GBP", "languages": "en-GB,cy-GB,gd", "asn": "AS1299", "org": "Telia Company AB" }, { "ip": "62.115.121.220", "city": "Frankfurt am Main", "region": "Hesse", "region_code": "HE", "country": "DE", "country_name": "Germany", "continent_code": "EU", "in_eu": true, "postal": "60313", "latitude": 50.1155, "longitude": 8.6842, "timezone": "Europe/Berlin", "utc_offset": "+0200", "country_calling_code": "+49", "currency": "EUR", "languages": "de", "asn": "AS1299", "org": "Telia Company AB" }, { "ip": "62.115.114.86", "city": "Ashburn", "region": "Virginia", "region_code": "VA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "20170", "latitude": 38.9841, "longitude": -77.3672, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS1299", "org": "Telia Company AB" }, { "ip": "62.115.121.220", "city": "Frankfurt am Main", "region": "Hesse", "region_code": "HE", "country": "DE", "country_name": "Germany", "continent_code": "EU", "in_eu": true, "postal": "60313", "latitude": 50.1155, "longitude": 8.6842, "timezone": "Europe/Berlin", "utc_offset": "+0200", "country_calling_code": "+49", "currency": "EUR", "languages": "de", "asn": "AS1299", "org": "Telia Company AB" }, { "ip": "219.158.34.253", "city": "Jinrongjie", "region": "Beijing", "region_code": null, "country": "CN", "country_name": "China", "continent_code": "AS", "in_eu": false, "postal": null, "latitude": null, "longitude": null, "timezone": null, "utc_offset": null, "country_calling_code": "+86", "currency": "CNY", "languages": "zh-CN,yue,wuu,dta,ug,za", "asn": "AS4837", "org": "CHINA UNICOM China169 Backbone" }, { "ip": "219.158.34.245", "city": "Jinrongjie", "region": "Beijing", "region_code": null, "country": "CN", "country_name": "China", "continent_code": "AS", "in_eu": false, "postal": null, "latitude": null, "longitude": null, "timezone": null, "utc_offset": null, "country_calling_code": "+86", "currency": "CNY", "languages": "zh-CN,yue,wuu,dta,ug,za", "asn": "AS4837", "org": "CHINA UNICOM China169 Backbone" }, { "ip": "219.158.34.249", "city": "Jinrongjie", "region": "Beijing", "region_code": null, "country": "CN", "country_name": "China", "continent_code": "AS", "in_eu": false, "postal": null, "latitude": null, "longitude": null, "timezone": null, "utc_offset": null, "country_calling_code": "+86", "currency": "CNY", "languages": "zh-CN,yue,wuu,dta,ug,za", "asn": "AS4837", "org": "CHINA UNICOM China169 Backbone" }, { "ip": "219.158.96.25", "city": "Guangzhou", "region": "Guangdong", "region_code": "GD", "country": "CN", "country_name": "China", "continent_code": "AS", "in_eu": false, "postal": null, "latitude": 23.1167, "longitude": 113.25, "timezone": "Asia/Shanghai", "utc_offset": "+0800", "country_calling_code": "+86", "currency": "CNY", "languages": "zh-CN,yue,wuu,dta,ug,za", "asn": "AS4837", "org": "CHINA UNICOM China169 Backbone" }, { "ip": "219.158.16.65", "city": "Jinrongjie", "region": "Beijing", "region_code": null, "country": "CN", "country_name": "China", "continent_code": "AS", "in_eu": false, "postal": null, "latitude": null, "longitude": null, "timezone": null, "utc_offset": null, "country_calling_code": "+86", "currency": "CNY", "languages": "zh-CN,yue,wuu,dta,ug,za", "asn": "AS4837", "org": "CHINA UNICOM China169 Backbone" }, { "ip": "219.158.5.153", "city": "Jinrongjie", "region": "Beijing", "region_code": null, "country": "CN", "country_name": "China", "continent_code": "AS", "in_eu": false, "postal": null, "latitude": null, "longitude": null, "timezone": null, "utc_offset": null, "country_calling_code": "+86", "currency": "CNY", "languages": "zh-CN,yue,wuu,dta,ug,za", "asn": "AS4837", "org": "CHINA UNICOM China169 Backbone" }, { "ip": "125.33.186.6", "city": "Beijing", "region": "Beijing", "region_code": "BJ", "country": "CN", "country_name": "China", "continent_code": "AS", "in_eu": false, "postal": null, "latitude": 39.9288, "longitude": 116.3889, "timezone": "Asia/Shanghai", "utc_offset": "+0800", "country_calling_code": "+86", "currency": "CNY", "languages": "zh-CN,yue,wuu,dta,ug,za", "asn": "AS4808", "org": "China Unicom Beijing Province Network" }, { "ip": "61.148.152.18", "city": "Beijing", "region": "Beijing", "region_code": "BJ", "country": "CN", "country_name": "China", "continent_code": "AS", "in_eu": false, "postal": null, "latitude": 39.9288, "longitude": 116.3889, "timezone": "Asia/Shanghai", "utc_offset": "+0800", "country_calling_code": "+86", "currency": "CNY", "languages": "zh-CN,yue,wuu,dta,ug,za", "asn": "AS4808", "org": "China Unicom Beijing Province Network" }, { "ip": "123.125.248.126", "city": "Beijing", "region": "Beijing", "region_code": "BJ", "country": "CN", "country_name": "China", "continent_code": "AS", "in_eu": false, "postal": null, "latitude": 39.9288, "longitude": 116.3889, "timezone": "Asia/Shanghai", "utc_offset": "+0800", "country_calling_code": "+86", "currency": "CNY", "languages": "zh-CN,yue,wuu,dta,ug,za", "asn": "AS4808", "org": "China Unicom Beijing Province Network" }, { "ip": "123.125.114.144", "city": "Beijing", "region": "Beijing", "region_code": "BJ", "country": "CN", "country_name": "China", "continent_code": "AS", "in_eu": false, "postal": null, "latitude": 39.9288, "longitude": 116.3889, "timezone": "Asia/Shanghai", "utc_offset": "+0800", "country_calling_code": "+86", "currency": "CNY", "languages": "zh-CN,yue,wuu,dta,ug,za", "asn": "AS4808", "org": "China Unicom Beijing Province Network" }]
const input_data_vk_com = [{ "ip": "193.73.125.35", "city": "Windisch", "region": "Aargau", "region_code": "AG", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "5210", "latitude": 47.479, "longitude": 8.2184, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "192.43.192.19", "city": "Basel", "region": "Basel-City", "region_code": "BS", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "4001", "latitude": 47.5584, "longitude": 7.5733, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.39.74", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.39.77", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.37.146", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.36.5", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "87.240.129.133", "city": "St Petersburg", "region": "St.-Petersburg", "region_code": "SPE", "country": "RU", "country_name": "Russia", "continent_code": "EU", "in_eu": false, "postal": "190817", "latitude": 59.8981, "longitude": 30.2619, "timezone": "Europe/Moscow", "utc_offset": "+0300", "country_calling_code": "+7", "currency": "RUB", "languages": "ru,tt,xal,cau,ady,kv,ce,tyv,cv,udm,tut,mns,bua,myv,mdf,chm,ba,inh,tut,kbd,krc,av,sah,nog", "asn": "AS47541", "org": "VKontakte Ltd" }]
const input_data_spotify = [{ "ip": "193.73.125.35", "city": "Windisch", "region": "Aargau", "region_code": "AG", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "5210", "latitude": 47.479, "longitude": 8.2184, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "192.43.192.196", "city": "Basel", "region": "Basel-City", "region_code": "BS", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "4001", "latitude": 47.5584, "longitude": 7.5733, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.37.34", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.36.170", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "72.14.195.4", "city": "Ashburn", "region": "Virginia", "region_code": "VA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "20170", "latitude": 38.9841, "longitude": -77.3672, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS15169", "org": "Google LLC" }, { "ip": "74.125.243.162", "city": "Ashburn", "region": "Virginia", "region_code": "VA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "20170", "latitude": 38.9841, "longitude": -77.3672, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS15169", "org": "Google LLC" }, { "ip": "74.125.243.165", "city": "Ashburn", "region": "Virginia", "region_code": "VA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "20170", "latitude": 38.9841, "longitude": -77.3672, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS15169", "org": "Google LLC" }, { "ip": "74.125.37.190", "city": "Newark", "region": "New Jersey", "region_code": "NJ", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "07175", "latitude": 40.739, "longitude": -74.1697, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS15169", "org": "Google LLC" }, { "ip": "209.85.241.134", "city": "Newark", "region": "New Jersey", "region_code": "NJ", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "07175", "latitude": 40.739, "longitude": -74.1697, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS15169", "org": "Google LLC" }, { "ip": "209.85.250.170", "city": "Ashburn", "region": "Virginia", "region_code": "VA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "20170", "latitude": 38.9841, "longitude": -77.3672, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS15169", "org": "Google LLC" }, { "ip": "66.249.95.226", "city": "Newark", "region": "New Jersey", "region_code": "NJ", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "07175", "latitude": 40.739, "longitude": -74.1697, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS15169", "org": "Google LLC" }, { "ip": "64.233.174.143", "city": "Newark", "region": "New Jersey", "region_code": "NJ", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "07175", "latitude": 40.739, "longitude": -74.1697, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS15169", "org": "Google LLC" }, { "ip": "66.249.94.153", "city": "Ashburn", "region": "Virginia", "region_code": "VA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "20170", "latitude": 38.9841, "longitude": -77.3672, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS15169", "org": "Google LLC" }, { "ip": "209.85.142.95", "city": "Ashburn", "region": "Virginia", "region_code": "VA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "20170", "latitude": 38.9841, "longitude": -77.3672, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS15169", "org": "Google LLC" }, { "ip": "108.170.231.183", "city": "Newark", "region": "New Jersey", "region_code": "NJ", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "07175", "latitude": 40.739, "longitude": -74.1697, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS15169", "org": "Google LLC" }, { "ip": "108.170.231.145", "city": "Newark", "region": "New Jersey", "region_code": "NJ", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "07175", "latitude": 40.739, "longitude": -74.1697, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS15169", "org": "Google LLC" }, { "ip": "108.170.232.3", "city": "Newark", "region": "New Jersey", "region_code": "NJ", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "07175", "latitude": 40.739, "longitude": -74.1697, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS15169", "org": "Google LLC" }, { "ip": "108.170.238.215", "city": "Ashburn", "region": "Virginia", "region_code": "VA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "20170", "latitude": 38.9841, "longitude": -77.3672, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS15169", "org": "Google LLC" }, { "ip": "104.199.64.136", "city": "Mountain View", "region": "California", "region_code": "CA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "94043", "latitude": 37.4043, "longitude": -122.0748, "timezone": "America/Los_Angeles", "utc_offset": "-0700", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS15169", "org": "Google LLC" }]
const input_data_naver = [{ "ip": "193.73.125.34", "city": "Windisch", "region": "Aargau", "region_code": "AG", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "5210", "latitude": 47.479, "longitude": 8.2184, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "192.43.192.196", "city": "Basel", "region": "Basel-City", "region_code": "BS", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "4001", "latitude": 47.5584, "longitude": 7.5733, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.39.74", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.39.77", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.37.146", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.36.5", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "80.249.211.220", "city": "Amsterdam", "region": "North Holland", "region_code": "NH", "country": "NL", "country_name": "Netherlands", "continent_code": "EU", "in_eu": true, "postal": "1091", "latitude": 52.3534, "longitude": 4.9087, "timezone": "Europe/Amsterdam", "utc_offset": "+0200", "country_calling_code": "+31", "currency": "EUR", "languages": "nl-NL,fy-NL", "asn": "AS1200", "org": "Amsterdam Internet Exchange B.V." }, { "ip": "210.89.160.88", "city": "Seongnam-si", "region": "Gyeonggi-do", "region_code": "41", "country": "KR", "country_name": "South Korea", "continent_code": "AS", "in_eu": false, "postal": null, "latitude": 37.4388, "longitude": 127.1396, "timezone": "Asia/Seoul", "utc_offset": "+0900", "country_calling_code": "+82", "currency": "KRW", "languages": "ko-KR,en", "asn": "AS23576", "org": "NBP" }]
const input_data_twitter = [{ "ip": "193.73.125.35", "city": "Windisch", "region": "Aargau", "region_code": "AG", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "5210", "latitude": 47.479, "longitude": 8.2184, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "192.43.192.196", "city": "Basel", "region": "Basel-City", "region_code": "BS", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "4001", "latitude": 47.5584, "longitude": 7.5733, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.39.74", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.39.77", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.37.146", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.36.5", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "80.249.208.130", "city": "Amsterdam", "region": "North Holland", "region_code": "NH", "country": "NL", "country_name": "Netherlands", "continent_code": "EU", "in_eu": true, "postal": "1091", "latitude": 52.3534, "longitude": 4.9087, "timezone": "Europe/Amsterdam", "utc_offset": "+0200", "country_calling_code": "+31", "currency": "EUR", "languages": "nl-NL,fy-NL", "asn": "AS1200", "org": "Amsterdam Internet Exchange B.V." }, { "ip": "104.244.42.193", "city": "San Francisco", "region": "California", "region_code": "CA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "94103", "latitude": 37.7771, "longitude": -122.406, "timezone": "America/Los_Angeles", "utc_offset": "-0700", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS13414", "org": "Twitter Inc." }]
const input_data_youtube = [{ "ip": "193.73.125.34", "city": "Windisch", "region": "Aargau", "region_code": "AG", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "5210", "latitude": 47.479, "longitude": 8.2184, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.37.34", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.36.170", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "72.14.195.4", "city": "Ashburn", "region": "Virginia", "region_code": "VA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "20170", "latitude": 38.9841, "longitude": -77.3672, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS15169", "org": "Google LLC" }, { "ip": "74.125.243.161", "city": "Ashburn", "region": "Virginia", "region_code": "VA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "20170", "latitude": 38.9841, "longitude": -77.3672, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS15169", "org": "Google LLC" }, { "ip": "74.125.243.145", "city": "Ashburn", "region": "Virginia", "region_code": "VA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "20170", "latitude": 38.9841, "longitude": -77.3672, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS15169", "org": "Google LLC" }, { "ip": "74.125.243.161", "city": "Ashburn", "region": "Virginia", "region_code": "VA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "20170", "latitude": 38.9841, "longitude": -77.3672, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS15169", "org": "Google LLC" }, { "ip": "172.253.50.21", "city": "Ashburn", "region": "Virginia", "region_code": "VA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "20170", "latitude": 38.9841, "longitude": -77.3672, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS15169", "org": "Google LLC" }, { "ip": "216.58.215.238", "city": "Mountain View", "region": "California", "region_code": "CA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "94043", "latitude": 37.4043, "longitude": -122.0748, "timezone": "America/Los_Angeles", "utc_offset": "-0700", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS15169", "org": "Google LLC" }]
const input_data_dazeddigital = [{ "ip": "193.73.125.34", "city": "Windisch", "region": "Aargau", "region_code": "AG", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "5210", "latitude": 47.479, "longitude": 8.2184, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "192.43.192.196", "city": "Basel", "region": "Basel-City", "region_code": "BS", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "4001", "latitude": 47.5584, "longitude": 7.5733, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.37.34", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.36.170", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "91.206.52.152", "city": "Opfikon", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8152", "latitude": 47.4317, "longitude": 8.5759, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm" }, { "ip": "104.44.232.99", "city": "Cape Town", "region": "Western Cape", "region_code": "WC", "country": "ZA", "country_name": "South Africa", "continent_code": "AF", "in_eu": false, "postal": "7405", "latitude": -33.9165, "longitude": 18.4155, "timezone": "Africa/Johannesburg", "utc_offset": "+0200", "country_calling_code": "+27", "currency": "ZAR", "languages": "zu,xh,af,nso,en-ZA,tn,st,ts,ss,ve,nr", "asn": "AS8075", "org": "Microsoft Corporation" }, { "ip": "104.44.20.247", "city": "Singapore", "region": "Central Singapore", "region_code": null, "country": "SG", "country_name": "Singapore", "continent_code": "AS", "in_eu": false, "postal": null, "latitude": null, "longitude": null, "timezone": null, "utc_offset": null, "country_calling_code": "+65", "currency": "SGD", "languages": "cmn,en-SG,ms-SG,ta-SG,zh-SG", "asn": "AS8075", "org": "Microsoft Corporation" }, { "ip": "104.44.17.253", "city": "Redmond", "region": "Washington", "region_code": "WA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "98052", "latitude": 47.6722, "longitude": -122.1257, "timezone": "America/Los_Angeles", "utc_offset": "-0700", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS8075", "org": "Microsoft Corporation" }, { "ip": "104.44.18.49", "city": "New York", "region": "New York", "region_code": "NY", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "10023", "latitude": 40.782, "longitude": -73.9953, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS8075", "org": "Microsoft Corporation" }, { "ip": "104.44.17.253", "city": "Redmond", "region": "Washington", "region_code": "WA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "98052", "latitude": 47.6722, "longitude": -122.1257, "timezone": "America/Los_Angeles", "utc_offset": "-0700", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS8075", "org": "Microsoft Corporation" }, { "ip": "104.44.18.6", "city": "New York", "region": "New York", "region_code": "NY", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "10023", "latitude": 40.782, "longitude": -73.9953, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS8075", "org": "Microsoft Corporation" }, { "ip": "104.44.18.4", "city": "New York", "region": "New York", "region_code": "NY", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "10023", "latitude": 40.782, "longitude": -73.9953, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS8075", "org": "Microsoft Corporation" }, { "ip": "104.44.18.6", "city": "New York", "region": "New York", "region_code": "NY", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "10023", "latitude": 40.782, "longitude": -73.9953, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS8075", "org": "Microsoft Corporation" }, { "ip": "104.44.7.215", "city": "Hong Kong", "region": "Central and Western", "region_code": null, "country": "HK", "country_name": "Hong Kong", "continent_code": "AS", "in_eu": false, "postal": null, "latitude": null, "longitude": null, "timezone": null, "utc_offset": null, "country_calling_code": "+852", "currency": "HKD", "languages": "zh-HK,yue,zh,en", "asn": "AS8075", "org": "Microsoft Corporation" }, { "ip": "104.44.17.79", "city": "Redmond", "region": "Washington", "region_code": "WA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "98052", "latitude": 47.6722, "longitude": -122.1257, "timezone": "America/Los_Angeles", "utc_offset": "-0700", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS8075", "org": "Microsoft Corporation" }, { "ip": "104.44.17.86", "city": "Redmond", "region": "Washington", "region_code": "WA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "98052", "latitude": 47.6722, "longitude": -122.1257, "timezone": "America/Los_Angeles", "utc_offset": "-0700", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS8075", "org": "Microsoft Corporation" }, { "ip": "104.44.11.56", "city": "New York", "region": "New York", "region_code": "NY", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "10023", "latitude": 40.782, "longitude": -73.9953, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS8075", "org": "Microsoft Corporation" }, { "ip": "104.44.11.76", "city": "New York", "region": "New York", "region_code": "NY", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "10023", "latitude": 40.782, "longitude": -73.9953, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS8075", "org": "Microsoft Corporation" }, { "ip": "23.102.21.198", "city": "Dublin", "region": "Leinster", "region_code": "L", "country": "IE", "country_name": "Ireland", "continent_code": "EU", "in_eu": true, "postal": "D02", "latitude": 53.3338, "longitude": -6.2488, "timezone": "Europe/Dublin", "utc_offset": "+0100", "country_calling_code": "+353", "currency": "EUR", "languages": "en-IE,ga-IE", "asn": "AS8075", "org": "Microsoft Corporation" }]
const input_data_crunchyroll = [{ "ip": "193.73.125.34", "city": "Windisch", "region": "Aargau", "region_code": "AG", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "5210", "latitude": 47.479, "longitude": 8.2184, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "192.43.192.196", "city": "Basel", "region": "Basel-City", "region_code": "BS", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "4001", "latitude": 47.5584, "longitude": 7.5733, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.37.34", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.36.170", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "91.206.52.192", "city": "Opfikon", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8152", "latitude": 47.4317, "longitude": 8.5759, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm" }, { "ip": "104.20.19.239", "city": "Ashburn", "region": "Virginia", "region_code": "VA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "20170", "latitude": 38.9841, "longitude": -77.3672, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS13335", "org": "Cloudflare, Inc." }]
const input_data_depop = [{ "ip": "193.73.125.34", "city": "Windisch", "region": "Aargau", "region_code": "AG", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "5210", "latitude": 47.479, "longitude": 8.2184, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "192.43.192.196", "city": "Basel", "region": "Basel-City", "region_code": "BS", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "4001", "latitude": 47.5584, "longitude": 7.5733, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.39.74", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.39.77", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.37.146", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.36.5", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "83.97.88.153", "city": "Cambridge", "region": "England", "region_code": "ENG", "country": "GB", "country_name": "United Kingdom", "continent_code": "EU", "in_eu": true, "postal": "CB5", "latitude": 52.2124, "longitude": 0.1534, "timezone": "Europe/London", "utc_offset": "+0100", "country_calling_code": "+44", "currency": "GBP", "languages": "en-GB,cy-GB,gd", "asn": "AS21320", "org": "GEANT Vereniging" }, { "ip": "62.40.98.180", "city": "Cambridge", "region": "England", "region_code": "ENG", "country": "GB", "country_name": "United Kingdom", "continent_code": "EU", "in_eu": true, "postal": "CB5", "latitude": 52.2124, "longitude": 0.1534, "timezone": "Europe/London", "utc_offset": "+0100", "country_calling_code": "+44", "currency": "GBP", "languages": "en-GB,cy-GB,gd", "asn": "AS20965", "org": "GEANT Vereniging" }, { "ip": "151.101.64.65", "city": "Ashburn", "region": "Virginia", "region_code": "VA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "20170", "latitude": 38.9841, "longitude": -77.3672, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS54113", "org": "Fastly" }]
const input_data_australia_gov_au = [{ "ip": "193.73.125.34", "city": "Windisch", "region": "Aargau", "region_code": "AG", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "5210", "latitude": 47.479, "longitude": 8.2184, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "192.43.192.196", "city": "Basel", "region": "Basel-City", "region_code": "BS", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "4001", "latitude": 47.5584, "longitude": 7.5733, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.37.34", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.36.170", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.38.109", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "213.248.79.189", "city": "New York", "region": "New York", "region_code": "NY", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "10023", "latitude": 40.782, "longitude": -73.9953, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS1299", "org": "Telia Company AB" }, { "ip": "62.115.116.126", "city": "London", "region": "England", "region_code": "ENG", "country": "GB", "country_name": "United Kingdom", "continent_code": "EU", "in_eu": true, "postal": "SE15", "latitude": 51.4663, "longitude": -0.051, "timezone": "Europe/London", "utc_offset": "+0100", "country_calling_code": "+44", "currency": "GBP", "languages": "en-GB,cy-GB,gd", "asn": "AS1299", "org": "Telia Company AB" }, { "ip": "62.115.147.79", "city": "Frankfurt am Main", "region": "Hesse", "region_code": "HE", "country": "DE", "country_name": "Germany", "continent_code": "EU", "in_eu": true, "postal": "60313", "latitude": 50.1155, "longitude": 8.6842, "timezone": "Europe/Berlin", "utc_offset": "+0200", "country_calling_code": "+49", "currency": "EUR", "languages": "de", "asn": "AS1299", "org": "Telia Company AB" }, { "ip": "129.250.3.178", "city": "San Jose", "region": "California", "region_code": "CA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "95141", "latitude": 37.3388, "longitude": -121.8914, "timezone": "America/Los_Angeles", "utc_offset": "-0700", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS2914", "org": "NTT America, Inc." }, { "ip": "129.250.4.69", "city": "Milpitas", "region": "California", "region_code": "CA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "95035", "latitude": 37.4371, "longitude": -121.8954, "timezone": "America/Los_Angeles", "utc_offset": "-0700", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS2914", "org": "NTT America, Inc." }, { "ip": "129.250.6.162", "city": "Milpitas", "region": "California", "region_code": "CA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "95035", "latitude": 37.4371, "longitude": -121.8954, "timezone": "America/Los_Angeles", "utc_offset": "-0700", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS2914", "org": "NTT America, Inc." }, { "ip": "129.250.3.84", "city": "San Jose", "region": "California", "region_code": "CA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "95141", "latitude": 37.3388, "longitude": -121.8914, "timezone": "America/Los_Angeles", "utc_offset": "-0700", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS2914", "org": "NTT America, Inc." }, { "ip": "129.250.3.189", "city": "San Jose", "region": "California", "region_code": "CA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "95141", "latitude": 37.3388, "longitude": -121.8914, "timezone": "America/Los_Angeles", "utc_offset": "-0700", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS2914", "org": "NTT America, Inc." }, { "ip": "129.250.3.238", "city": "San Jose", "region": "California", "region_code": "CA", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "95141", "latitude": 37.3388, "longitude": -121.8914, "timezone": "America/Los_Angeles", "utc_offset": "-0700", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS2914", "org": "NTT America, Inc." }, { "ip": "129.250.201.90", "city": "Chicago", "region": "Illinois", "region_code": "IL", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "60618", "latitude": 41.946, "longitude": -87.7033, "timezone": "America/Chicago", "utc_offset": "-0500", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS2914", "org": "NTT America, Inc." }, { "ip": "129.250.201.66", "city": "Chicago", "region": "Illinois", "region_code": "IL", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "60618", "latitude": 41.946, "longitude": -87.7033, "timezone": "America/Chicago", "utc_offset": "-0500", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS2914", "org": "NTT America, Inc." }, { "ip": "54.252.130.223", "city": "Sydney", "region": "New South Wales", "region_code": "NSW", "country": "AU", "country_name": "Australia", "continent_code": "OC", "in_eu": false, "postal": "2000", "latitude": -33.8591, "longitude": 151.2002, "timezone": "Australia/Sydney", "utc_offset": "+1000", "country_calling_code": "+61", "currency": "AUD", "languages": "en-AU", "asn": "AS16509", "org": "Amazon.com, Inc." }]
const input_data_easyjet = [{ "ip": "193.73.125.35", "city": "Windisch", "region": "Aargau", "region_code": "AG", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "5210", "latitude": 47.479, "longitude": 8.2184, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "192.43.192.196", "city": "Basel", "region": "Basel-City", "region_code": "BS", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "4001", "latitude": 47.5584, "longitude": 7.5733, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.37.34", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.36.170", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "130.59.38.109", "city": "Zurich", "region": "Zurich", "region_code": "ZH", "country": "CH", "country_name": "Switzerland", "continent_code": "EU", "in_eu": false, "postal": "8002", "latitude": 47.3664, "longitude": 8.5546, "timezone": "Europe/Zurich", "utc_offset": "+0200", "country_calling_code": "+41", "currency": "CHF", "languages": "de-CH,fr-CH,it-CH,rm", "asn": "AS559", "org": "SWITCH" }, { "ip": "213.248.79.189", "city": "New York", "region": "New York", "region_code": "NY", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "10023", "latitude": 40.782, "longitude": -73.9953, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS1299", "org": "Telia Company AB" }, { "ip": "62.115.142.110", "city": "London", "region": "England", "region_code": "ENG", "country": "GB", "country_name": "United Kingdom", "continent_code": "EU", "in_eu": true, "postal": "SE15", "latitude": 51.4663, "longitude": -0.051, "timezone": "Europe/London", "utc_offset": "+0100", "country_calling_code": "+44", "currency": "GBP", "languages": "en-GB,cy-GB,gd", "asn": "AS1299", "org": "Telia Company AB" }, { "ip": "62.115.142.104", "city": "London", "region": "England", "region_code": "ENG", "country": "GB", "country_name": "United Kingdom", "continent_code": "EU", "in_eu": true, "postal": "SE15", "latitude": 51.4663, "longitude": -0.051, "timezone": "Europe/London", "utc_offset": "+0100", "country_calling_code": "+44", "currency": "GBP", "languages": "en-GB,cy-GB,gd", "asn": "AS1299", "org": "Telia Company AB" }, { "ip": "62.115.142.110", "city": "London", "region": "England", "region_code": "ENG", "country": "GB", "country_name": "United Kingdom", "continent_code": "EU", "in_eu": true, "postal": "SE15", "latitude": 51.4663, "longitude": -0.051, "timezone": "Europe/London", "utc_offset": "+0100", "country_calling_code": "+44", "currency": "GBP", "languages": "en-GB,cy-GB,gd", "asn": "AS1299", "org": "Telia Company AB" }, { "ip": "62.115.142.47", "city": "London", "region": "England", "region_code": "ENG", "country": "GB", "country_name": "United Kingdom", "continent_code": "EU", "in_eu": true, "postal": "SE15", "latitude": 51.4663, "longitude": -0.051, "timezone": "Europe/London", "utc_offset": "+0100", "country_calling_code": "+44", "currency": "GBP", "languages": "en-GB,cy-GB,gd", "asn": "AS1299", "org": "Telia Company AB" }, { "ip": "62.115.142.5", "city": "London", "region": "England", "region_code": "ENG", "country": "GB", "country_name": "United Kingdom", "continent_code": "EU", "in_eu": true, "postal": "SE15", "latitude": 51.4663, "longitude": -0.051, "timezone": "Europe/London", "utc_offset": "+0100", "country_calling_code": "+44", "currency": "GBP", "languages": "en-GB,cy-GB,gd", "asn": "AS1299", "org": "Telia Company AB" }, { "ip": "62.115.56.146", "city": "Frankfurt am Main", "region": "Hesse", "region_code": "HE", "country": "DE", "country_name": "Germany", "continent_code": "EU", "in_eu": true, "postal": "60313", "latitude": 50.1155, "longitude": 8.6842, "timezone": "Europe/Berlin", "utc_offset": "+0200", "country_calling_code": "+49", "currency": "EUR", "languages": "de", "asn": "AS1299", "org": "Telia Company AB" }, { "ip": "67.14.100.126", "city": "Dallas", "region": "Texas", "region_code": "TX", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "75207", "latitude": 32.7908, "longitude": -96.8336, "timezone": "America/Chicago", "utc_offset": "-0500", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS209", "org": "CenturyLink Communications, LLC" }, { "ip": "216.35.242.157", "city": "Chicago", "region": "Illinois", "region_code": "IL", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "60618", "latitude": 41.946, "longitude": -87.7033, "timezone": "America/Chicago", "utc_offset": "-0500", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS3561", "org": "CenturyLink Communications, LLC" }, { "ip": "216.35.240.85", "city": "L'Hospitalet de Llobregat", "region": "Catalonia", "region_code": "CT", "country": "ES", "country_name": "Spain", "continent_code": "EU", "in_eu": true, "postal": "08904", "latitude": 41.4301, "longitude": 2.1925, "timezone": "Europe/Madrid", "utc_offset": "+0200", "country_calling_code": "+34", "currency": "EUR", "languages": "es-ES,ca,gl,eu,oc", "asn": "AS3561", "org": "CenturyLink Communications, LLC" }, { "ip": "216.35.240.81", "city": "L'Hospitalet de Llobregat", "region": "Catalonia", "region_code": "CT", "country": "ES", "country_name": "Spain", "continent_code": "EU", "in_eu": true, "postal": "08904", "latitude": 41.4301, "longitude": 2.1925, "timezone": "Europe/Madrid", "utc_offset": "+0200", "country_calling_code": "+34", "currency": "EUR", "languages": "es-ES,ca,gl,eu,oc", "asn": "AS3561", "org": "CenturyLink Communications, LLC" }, { "ip": "205.138.33.38", "city": "New York", "region": "New York", "region_code": "NY", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "10023", "latitude": 40.782, "longitude": -73.9953, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS3561", "org": "CenturyLink Communications, LLC" }, { "ip": "205.138.33.42", "city": "New York", "region": "New York", "region_code": "NY", "country": "US", "country_name": "United States", "continent_code": "NA", "in_eu": false, "postal": "10023", "latitude": 40.782, "longitude": -73.9953, "timezone": "America/New_York", "utc_offset": "-0400", "country_calling_code": "+1", "currency": "USD", "languages": "en-US,es-US,haw,fr", "asn": "AS3561", "org": "CenturyLink Communications, LLC" }, { "ip": "206.150.181.10", "city": "Luton", "region": "England", "region_code": "ENG", "country": "GB", "country_name": "United Kingdom", "continent_code": "EU", "in_eu": true, "postal": "LU2", "latitude": 51.9114, "longitude": -0.382, "timezone": "Europe/London", "utc_offset": "+0100", "country_calling_code": "+44", "currency": "GBP", "languages": "en-GB,cy-GB,gd", "asn": "AS3561", "org": "CenturyLink Communications, LLC" }]

const data = [
    input_data_yahoo_jp,
    input_data_pornhub,
    input_data_twitter,
    input_data_dazeddigital,
    input_data_australia_gov_au,
    input_data_easyjet,

]


const data_txt = [
    'yahoo.co.jp',
    'pornhub.com',
    'twitter.com',
    'dazeddigital.com',
    'australia.gov.au',
    'easyjet.com',

]
